# Generated by Django 2.2.1 on 2020-02-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmTrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='commission_pct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
